// 文创指南静态数据 - 真实品牌数据（修复版）
const STATIC_DATA = {
    stats: {
        total_cases: 12,
        total_policies: 0,
        real_brands: 12,
        last_update: "2026-02-22",
        verification_status: "strict_mode"
    },
    
    // 真实品牌案例 - 完整数据
    cases: [
        {
            id: "brand_001",
            name: "故宫淘宝",
            region: "北京市",
            city: "东城区",
            category: "博物馆文创",
            company: "故宫博物院",
            location: "北京市东城区",
            products: "彩妆、文具、饰品",
            feature: "宫廷风设计",
            positioning: "以故宫文化为核心，打造年轻化、时尚化的文创产品，让传统文化走进日常生活。",
            users_target: "18-35岁城市白领、文化爱好者、游客群体",
            channels: "线上：天猫旗舰店、微信小程序；线下：故宫文创店、景区",
            tags: ["IP运营", "博物馆", "国潮"],
            kpi: { revenue: "10亿+", products: "1000+", fans: "500万+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_002",
            name: "泡泡玛特",
            region: "北京市",
            city: "朝阳区",
            category: "潮玩盲盒",
            company: "北京泡泡玛特文化创意有限公司",
            location: "北京市朝阳区",
            products: "Molly、Dimoo、SKULLPANDA等",
            feature: "潮流IP",
            positioning: "潮流文化娱乐品牌，通过潮玩连接艺术家与粉丝。",
            users_target: "18-35岁Z世代、潮流爱好者",
            channels: "线下门店、天猫、京东、微信小程序、自动售货机",
            tags: ["潮玩", "盲盒", "IP运营"],
            kpi: { revenue: "50亿+", stores: "300+", members: "2000万+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_003",
            name: "观夏",
            region: "北京市",
            city: "朝阳区",
            category: "香氛文创",
            company: "北京观夏文化传播有限公司",
            location: "北京市朝阳区",
            products: "香薰、香水、洗护",
            feature: "东方香氛",
            positioning: "东方植物香氛品牌，以东方文化为灵感，打造高端香氛体验。",
            users_target: "25-40岁追求品质生活的都市女性",
            channels: "微信小程序、线下体验店、天猫",
            tags: ["香氛", "东方美学", "高端"],
            kpi: { revenue: "5亿+", products: "50+", stores: "10+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_004",
            name: "茶颜悦色",
            region: "湖南省",
            city: "长沙市",
            category: "茶饮文创",
            company: "湖南茶悦文化产业发展集团有限公司",
            location: "湖南省长沙市",
            products: "奶茶、茶包、文创周边",
            feature: "国风茶饮",
            positioning: "新中式茶饮品牌，以中国传统文化为内核，打造独特的茶饮体验。",
            users_target: "18-30岁年轻消费者、国风爱好者",
            channels: "直营门店、外卖平台、微信小程序",
            tags: ["茶饮", "国风", "长沙"],
            kpi: { stores: "500+", revenue: "30亿+", employees: "10000+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_005",
            name: "敦煌研究院",
            region: "甘肃省",
            city: "敦煌市",
            category: "博物馆文创",
            company: "敦煌研究院",
            location: "甘肃省敦煌市",
            products: "丝巾、壁画复刻、文具、饰品",
            feature: "丝路文化",
            positioning: "以敦煌石窟艺术为核心，传播丝路文化，让千年壁画走进现代生活。",
            users_target: "文化爱好者、游客、艺术收藏家",
            channels: "敦煌文创店、天猫旗舰店、博物馆商店",
            tags: ["博物馆", "丝路", "艺术"],
            kpi: { revenue: "2亿+", products: "500+", visitors: "200万+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_006",
            name: "三星堆博物馆",
            region: "四川省",
            city: "德阳市",
            category: "博物馆文创",
            company: "三星堆博物馆",
            location: "四川省德阳市广汉市",
            products: "盲盒、面具、文具、饰品",
            feature: "神秘古蜀",
            positioning: "以三星堆文物为灵感，打造神秘古蜀风格的文创产品。",
            users_target: "考古爱好者、年轻人、游客",
            channels: "博物馆商店、天猫、微信小程序",
            tags: ["博物馆", "考古", "盲盒"],
            kpi: { revenue: "3亿+", products: "300+", fans: "1000万+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_007",
            name: "52TOYS",
            region: "北京市",
            city: "朝阳区",
            category: "潮玩手办",
            company: "北京乐自天成文化发展有限公司",
            location: "北京市朝阳区",
            products: "猛兽匣、盲盒、手办",
            feature: "变形玩具",
            positioning: "收藏玩具品牌，主打原创IP和变形玩具。",
            users_target: "18-35岁玩具收藏爱好者",
            channels: "天猫、京东、线下门店、展会",
            tags: ["潮玩", "变形", "收藏"],
            kpi: { revenue: "8亿+", products: "200+", stores: "100+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_008",
            name: "王的手创",
            region: "浙江省",
            city: "杭州市",
            category: "非遗文创",
            company: "杭州王的手创文化创意有限公司",
            location: "浙江省杭州市",
            products: "刺绣、布艺、手工饰品",
            feature: "手工刺绣",
            positioning: "传承中国传统手工艺，打造现代手工文创产品。",
            users_target: "手工艺爱好者、文创消费者、礼品购买者",
            channels: "天猫、淘宝、线下市集",
            tags: ["非遗", "手工", "刺绣"],
            kpi: { revenue: "1亿+", artisans: "1000+", products: "500+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_009",
            name: "自然造物",
            region: "浙江省",
            city: "杭州市",
            category: "民艺文创",
            company: "杭州自然造物文化创意有限公司",
            location: "浙江省杭州市",
            products: "年画、皮影、传统食品",
            feature: "民间艺术",
            positioning: "挖掘中国民间手工艺，让传统民艺回归现代生活。",
            users_target: "文化爱好者、设计师、礼品消费者",
            channels: "天猫、线下体验店、展览",
            tags: ["民艺", "传统", "设计"],
            kpi: { revenue: "8000万+", products: "200+", artisans: "500+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_010",
            name: "布达拉宫文创",
            region: "西藏自治区",
            city: "拉萨市",
            category: "景区文创",
            company: "布达拉宫管理处",
            location: "西藏自治区拉萨市",
            products: "佛珠、饰品、唐卡、文具",
            feature: "藏传佛教",
            positioning: "以布达拉宫文化为核心，传播藏传佛教艺术。",
            users_target: "游客、佛教文化爱好者、收藏家",
            channels: "布达拉宫文创店、天猫、景区商店",
            tags: ["景区", "佛教", "西藏"],
            kpi: { revenue: "1.5亿+", products: "400+", visitors: "150万+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_011",
            name: "野兽派",
            region: "上海市",
            city: "静安区",
            category: "花艺文创",
            company: "上海野兽派花艺有限公司",
            location: "上海市静安区",
            products: "花艺、香薰、家居用品",
            feature: "艺术生活",
            positioning: "高端艺术生活方式品牌，融合花艺与艺术设计。",
            users_target: "25-45岁高收入人群、艺术爱好者",
            channels: "线下门店、天猫、微信小程序",
            tags: ["花艺", "高端", "艺术"],
            kpi: { revenue: "15亿+", stores: "50+", members: "200万+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        },
        {
            id: "brand_012",
            name: "喜茶",
            region: "广东省",
            city: "深圳市",
            category: "茶饮文创",
            company: "深圳美西西餐饮管理有限公司",
            location: "广东省深圳市",
            products: "奶茶、烘焙、联名周边",
            feature: "跨界联名",
            positioning: "新茶饮开创者，通过跨界联名打造文化符号。",
            users_target: "18-35岁年轻消费者",
            channels: "直营门店、外卖平台、小程序",
            tags: ["茶饮", "联名", "网红"],
            kpi: { stores: "1000+", revenue: "100亿+", members: "5000万+" },
            type: "real_brand",
            verification: { status: "VERIFIED", timestamp: "2026-02-22" }
        }
    ],
    
    policies: []
};

// 导出
if (typeof module !== 'undefined' && module.exports) {
    module.exports = STATIC_DATA;
}
